### ISSUE TITLE
New Error 

### ISSUE THREAD

**Issue by Conathel** [Chase-san/TiTsEd#110]
Hope I'm doing this right, never reported an error before but here it is:

[C:\Users\Alan\Downloads\TiTsEd_v0.30.8\TiTsEd.exe:0.30.8.37283:Microsoft Windows NT 6.2.9200.0:Unknown]
System.Configuration.ConfigurationErrorsException: Failed to save settings: The configuration file has been changed by another program. (C:\Users\Alan\AppData\Local\TiTsEd\TiTsEd.exe_Url_djd24gpa1edn2sepvnc4gc0ax055tq32\0.30.8.37283\user.config) ---> System.Configuration.ConfigurationErrorsException: The configuration file has been changed by another program. (C:\Users\Alan\AppData\Local\TiTsEd\TiTsEd.exe_Url_djd24gpa1edn2sepvnc4gc0ax055tq32\0.30.8.37283\user.config)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at TiTsEd.MainWindow.SaveSizeAndState()
   at System.Windows.Window.WmMoveChangedHelper()
   at System.Windows.Window.WmMoveChanged()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by algoRhythm99** [comment]
This looks like you had two copies of the app running at the same time.
