### ISSUE TITLE
Root element is missing

### ISSUE THREAD

**Issue by Terrahtv1** [Chase-san/TiTsEd#115]
Not sure what this means but i keep getting it when trying to open the program and it won't let me open it. Also already tried to reinstall it and nothing.

[E:\New\TiTS\TiTsEd.exe:0.30.8.37283:Microsoft Windows NT 6.2.9200.0:Unknown]
System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Users\Hikaru\AppData\Local\TiTsEd\TiTsEd.exe_Url_cw5hdepegsvbkfn4hs3qxbrnsjxgn3ya\0.30.8.37283\user.config) ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties, Boolean isRoaming)
   at System.Configuration.LocalFileSettingsProvider.Upgrade(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.ApplicationSettingsBase.Upgrade()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by algoRhythm99** [comment]
Make TiTsEd is not running and delete C:\Users\Hikaru\AppData\Local\TiTsEd

**Comment by Terrahtv1** [comment]
Awesome, it worked. Thanks!
