### ISSUE TITLE
can't load save file on TITsEd

### ISSUE THREAD

**Issue by cr280** [Chase-san/TiTsEd#134]
I suddenly can't load new save file, but it didn't show any errors
I could still load some older save file but not the new ones

**Comment by algoRhythm99** [comment]
can you attach the save, or link it?

**Comment by algoRhythm99** [comment]
Also, attach the %LOCALAPPDATA%\TiTsEd\TiTsEd.log file

**Comment by cr280** [comment]
here is the link
https://drive.google.com/file/d/1Gyaq6tLHjK6SkEBD5gtEKvbN8nVGm3vS/view?usp=sharing

but weirdly I couldn't find the .log file in this location %LOCALAPPDATA%\TiTsEd\TiTsEd.log file
is it the text file??

and another thing when I tried to open the save file from the "external" tab I got this eror
 [D:\SteamLibrary\New folder\html\tit\TiTsEd.exe:0.34.4.0:Microsoft Windows NT 6.2.9200.0:33]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM)
   at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat)
   at TiTsEd.View.TopBar.SubMenu_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by algoRhythm99** [comment]
That save file has an unlockedCodexEntries value which is null, which shouldn't be possible.

**Comment by cr280** [comment]
Is there a way to fix it?? or should I just restart from the older save?

**Comment by algoRhythm99** [comment]
Can you try this version?
https://github.com/algoRhythm99/TiTsEd/releases/tag/v0.34.5

**Comment by cr280** [comment]
sure :D

**Comment by cr280** [comment]
it worked, thank you for your help :)
