### ISSUE TITLE
Support: Load issues

### ISSUE THREAD

**Issue by KieroVance** [Chase-san/TiTsEd#14]
is it just me doing something wrong? or something else? it CAN'T edit the normal save files as they have an extension of .tits.

here:

[TiTsEd: 0.11.0.33670]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.Model.AmfReader.ReadPlainDataFile(AmfFile file, String& name)
   at TiTsEd.Model.AmfFile..ctor(String path)

and if i click continue:

[TiTsEd: 0.11.0.33670]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM)
   at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
   at TiTsEd.ViewModel.ImportRootVM.OnClick()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Chase-san** [comment]
If you have to choose the file name you are doing it wrong. Do not use "Save File", just use Save in game and load the slot.

**Comment by KieroVance** [comment]
im confused, how do i edit it then? theres nothing i can see to edit the save file or ANY saves... i can't just make it GO INTO the browser and take the save, TITS is a swf, which make me open it into a browser, theres no other saves...mabye you could have a picture tutorial? because i see no way of how this works...im rather confused...im not saying it doesn't...im saying i dont see it... :\

**Comment by Chase-san** [comment]
It finds where the swf saves the files and then loads those. Just save using "save" and when you open the editor, click Open, then goto Local (Your Browser), where "Your Browser" is the name of your browser, and select the slot you saved in.

![image](https://cloud.githubusercontent.com/assets/34535/17460285/f5dbc07a-5c2c-11e6-9b18-4b010521f063.png)

In my case, I used Chrome, so I just goto Local (Chrome) and select the save. It's really not that complicated.
