### ISSUE TITLE
Item weirdness

### ISSUE THREAD

**Issue by BlackwaterSyn** [Chase-san/TiTsEd#24]
So, I got this weird thing happening: I tried removing an item from my inventory by changing its quanity to 0. Instead of that happening, the whole section went blank. When attempting to exit the editor, I got this:

`[TiTsEd: 0.13.0.1025, TiTs Data: 28]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.ViewModel.ItemGroupVM..ctor(String name, ItemSlotVM slot)
   at TiTsEd.ViewModel.ItemSlotVM.UpdateItemGroups()
   at TiTsEd.ViewModel.ItemContainerVM.Add(AmfObject obj)
   at TiTsEd.ViewModel.CharacterVM.UpdateInventory()
   at TiTsEd.ViewModel.CharacterVM..ctor(GameVM game, AmfObject obj)
   at TiTsEd.ViewModel.GameVM.setCharacter(String name)
   at TiTsEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM)
   at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

Here's hoping I pasted the error right this time.

**Comment by Chase-san** [comment]
Yes, I can reproduce this, it might be caused by something I did, i'll see about getting it fixed as soon as possible.

**Comment by Chase-san** [comment]
Found the issue, my string wasn't initialized. I'll upload a fixed copy in the next few minutes.

**Comment by BlackwaterSyn** [comment]
Wow that was fast. I came back to add that, while it closes the editor, the save file isn't harmed by whatever is happening, and it does, in fact, remove the item as intended... And you fixed it before I finished typing this, so I guess that info wasn't needed. 

You're good.

**Comment by Chase-san** [comment]
No no, if I was good I would have tested more and not caused the issue in the first place.

**Comment by BlackwaterSyn** [comment]
Can't account for everything, especially not something so small you would never think to check it. Even triple AAA games come out with bugs, and those usually have far more calamitous effects.
