### ISSUE TITLE
Cant seem to load in save to file format

### ISSUE THREAD

**Issue by FillerAccount** [Chase-san/TiTsEd#3]
For some reason, every time I try using TiTSEd on a "Save to File" format save, I get an error. When I try, first I get a "Could Not Read File" box with this error message:

[TiTsEd: 0.8.2.35843]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.Model.AmfReader.ReadPlainDataFile(AmfFile file, String& name)
   at TiTsEd.Model.AmfFile..ctor(String path)

And then when I click continue, I get an "Unexpected error" box with this error message.

[TiTsEd: 0.8.2.35843]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.ViewModel.GameVM.setCharacter(String name)
   at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

And then the program closes. I don't know any programming, so do you know what the error could be?

**Comment by Murphy540** [comment]
It's because TiTsEd can only read flash save files (.sol) and not TiTs exports (which is 'save to file'; they're .tits files)

**Comment by SHMUPsaffa** [comment]
how to make .sol?

**Comment by Chase-san** [comment]
I will remove this option for not until I can test and verify it. Sorry for the inconvenience.

**Comment by Chase-san** [comment]
I rescind that, it's fine, just it can only open .sol files as stated, that is save in a slot that you can browse to that folder and open it if the program itself cannot find the files.
