### ISSUE TITLE
Not sure exactly: Parsing error in file names?

### ISSUE THREAD

**Issue by xmghacks** [Chase-san/TiTsEd#41]
Error occurred while trying to load a "save to file format save" from my android device.

(Error details bellow)
[TiTsEd: 0.17.0.17389]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.Model.AmfReader.ReadPlainDataFile(AmfFile file, String& name)
   at TiTsEd.Model.AmfFile..ctor(String path)

 Also i got this when trying to continue (Screenshot bellow)
http://prntscr.com/di8gm3

(Third error message?)
[TiTsEd: 0.17.0.17389]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.ViewModel.GameVM.SetCharacterOptions()
   at TiTsEd.ViewModel.GameVM..ctor(AmfFile file, GameVM previousVM)
   at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
   at TiTsEd.ViewModel.ImportRootVM.OnClick()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Also, i can confirm that this was saved in (Save to file format) and is not in (Slot format).
I think that maybe the version of TiTS i'm running is incompatible with the save editor as of the moment, or the apk i'm using is not formatting saves correctly. Any ideas?

**Comment by Chase-san** [comment]
In theory, you would have to use this sequence. You have to "Save File" on android, copy that file to PC, load the file on PC "Load File", then save the file to slot, then open that slot in TiTsEd. Then reverse all that to put it back on Android.

**Comment by xmghacks** [comment]
Yea, this seems to be the only working method at the moment. Trying to export out of save to file format through TiTsED gives errors when loading back into the PC version. (Testing the saves to make sure they are functioning correctly). Thanks for the insight though, the fast response was nice aswell.
I will continue to look for any bugs, and let you know if i see anything.
