### ISSUE TITLE
window won't show up, and i got a really long error

### ISSUE THREAD

**Issue by billbobbill** [Chase-san/TiTsEd#69]
[TiTsEd: 0.25.3.41891]
System.IO.IOException: The process cannot access the file 'C:\Users\Zen\AppData\Local\TiTsEd\TiTsEd.exe_Url_40i3yp34rzljs4labhdzqloxerjijdam\0.25.3.41891\user.config' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForRead(String streamName)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForRead(String streamName, Boolean assertPermissions)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.ClientSettingsStore.WriteSettings(String sectionName, Boolean isRoaming, IDictionary newSettings)
   at System.Configuration.LocalFileSettingsProvider.SetPropertyValues(SettingsContext context, SettingsPropertyValueCollection values)
   at System.Configuration.SettingsBase.SaveCore()
   at System.Configuration.SettingsBase.Save()
   at System.Configuration.ApplicationSettingsBase.Save()
   at TiTsEd.MainWindow.SaveSizeAndState()
   at System.Windows.ContextLayoutManager.fireSizeChangedEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by DernaSteele** [comment]
The first line reveals the problem: 

> System.IO.IOException: The process cannot access the file 'C:\Users\Zen\AppData\Local\TiTsEd\TiTsEd.exe_Url_40i3yp34rzljs4labhdzqloxerjijdam\0.25.3.41891\user.config' because it is being used by another process.

Some process is using the user.config file and blocking access to it.

**Comment by billbobbill** [comment]
@DernaSteele thanks! i am not good at computers (my coding knowledge is limited to very basic binary)
would you mind if i ask you if you have any ideas on how to fix it?

**Comment by DernaSteele** [comment]
@billbobbill have you tried restarting your PC? The problem should not persist for a long period of time unless there is a process stuck, or you're running multiple copies of the program and they're interfering with each other. 

If you keep getting the same error (IOException, file being used by another process), download a program called LockHunter (or something similar), and run it on the conflicting file (in this case, user.config) and see what processes are currently using it.

**Comment by billbobbill** [comment]
@DernaSteele thank you! tried lockhunter, but it says nothing is locking the file now. now the app seems to open,  (as in the icon appears on the toolbar) but the window will NOT load. if you'd still be able to help, that would be much appreciated.

**Comment by DernaSteele** [comment]
Something must be corrupt. Should probably try redownloading the program and/or deleting/moving your save files.

**Comment by algoRhythm99** [comment]
This might be an anti-virus issue.
Did you unblock the zip file prior to unzipping?

**Comment by billbobbill** [comment]
@DernaSteele  i redownloaded before asking the question, and deleted my saves.
@algoRhythm99 i did unblock.

**Comment by algoRhythm99** [comment]
The only reason you should get that error is:
If you really don't have access to it for some reason (invalid security settings)
You have another copy of the application running that is trying to write to it at the same time
Bad anti-malware that is holding onto a handle to the file

Have you restarted and you still get the error?
If so, see if you can delete the file.

**Comment by billbobbill** [comment]
@algoRhythm99 deleted the file

**Comment by algoRhythm99** [comment]
So you aren't getting the error any more?

**Comment by algoRhythm99** [comment]
Closing
