### ISSUE TITLE
tried importing a .tits file, but crashes

### ISSUE THREAD

**Issue by Sumguy62** [Chase-san/TiTsEd#95]
[TiTsEd: 0.30.4.21537]
System.NullReferenceException: Object reference not set to an instance of an object.
   at TiTsEd.Model.FileManager.AreParentAndChild(String dirPath, String filePath)
   at TiTsEd.Model.FileManager.TryRegisterExternalFile(String path)
   at TiTsEd.ViewModel.VM.Load(String path, SerializationFormat expectedFormat, Boolean createBackup)
   at TiTsEd.ViewModel.ImportRootVM.OnClick()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Error occurs with both saves from TiTSversions that worked with older versions of TiTsEd, and with newest public TiTS saves.

**Comment by algoRhythm99** [comment]
I cannot reproduce this.
Can you link or attach the TiTsEd.log file that should be next to the exe?

**Comment by Sumguy62** [comment]
I don't see a TiTsEd.log. I see a .data, .exe.config, .exe, and that's it with TiTsEd.*

**Comment by Sumguy62** [comment]
It might have something to do with the fact that I'm using a VM and it's in a shared folder. When I dragged the file into the VM and used it from the VM's desktop, it worked fine.

**Comment by algoRhythm99** [comment]
Can you try this version?
https://github.com/Chase-san/TiTsEd/releases/tag/v0.30.4

**Comment by algoRhythm99** [comment]
Closing since no response, reopen if still an issue
